// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-7j33Pr-ct8E9DPAY7xyzLY_5jiu5kc0',
    appId: '1:756900195998:android:2a295b1f1497b752cc158f',
    messagingSenderId: '756900195998',
    projectId: 'assignment-5fa12',
    databaseURL: 'https://assignment-5fa12-default-rtdb.firebaseio.com',
    storageBucket: 'assignment-5fa12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaZRXqPxWZrTJ3PBhwUbrUtZR_IrRE-GA',
    appId: '1:756900195998:ios:80b8f54e15eb2b33cc158f',
    messagingSenderId: '756900195998',
    projectId: 'assignment-5fa12',
    databaseURL: 'https://assignment-5fa12-default-rtdb.firebaseio.com',
    storageBucket: 'assignment-5fa12.firebasestorage.app',
    androidClientId: '756900195998-kcffc2csk9k3iij0ujo31851thcgrulo.apps.googleusercontent.com',
    iosClientId: '756900195998-9skahn9c7p0plmnhcdo0ogr079riafi4.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignments',
  );
}
